; PlatformIO Project Configuration File
; Smart ePod - Dual Brain Architecture

; ------------------------------------------------
; BRAIN 1: ESP32 WROVER (Hardware & Audio UI)
; ------------------------------------------------
[env:esp-wrover-kit]
platform = espressif32
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit SSD1306 @ ^2.5.9